name: Snake Animation

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Contribution Snake
        uses: Platane/snk@master
        with:
          github_user: sanjanah8  # Replace with your GitHub username
          output: output/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake animation"
          git push
